### PR TITLE
Parametrized data directory

### LINKED ISSUE #88: Allow customizing data path
This is now hardcoded to `/mnt/data` and we would like to take this role into use but our convention is to use `/data`. Now I have to modify the role which introduces merge conflicts when we update it form upstream. Can you make it a variable in official repo?

UPD: Made PR for this since I already performed the necessary changes

### PR DESCRIPTION
**Pull request by megakoresh**
Resolves #88

### CODE REVIEW

**Comment by megakoresh** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement):
> [c8ced39](https://github.com/elastic/ansible-elastic-cloud-enterprise/commit/c8ced39ef19bb29aaeb9a41970eb748dc9629231)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

Maker's breath, you have quite the process. Took me longer to sign that document than to make these changes

**Review by obierlaire — APPROVED** [review]
Thanks for contributing @megakoresh ! After my little commit, your PR is passing our internal tests. LGTM!

**Comment by obierlaire** [comment]
@megakoresh Looks like you have signed the Contributor Agreement with a different email address that you configured in git. Also you might need to squash all your commits and have it pushed with the right author email. There is a bit of [documentation here](https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit#3042512) if you need.

**Comment by megakoresh** [comment]
> @megakoresh Looks like you have signed the Contributor Agreement with a different email address that you configured in git. Also you might need to squash all your commits and have it pushed with the right author email. There is a bit of [documentation here](https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit#3042512) if you need.

Ok it was not clear that the email in commit must be the same email as github and in the CLA. I have now done this and squashed all commits. Thanks!

**Comment by obierlaire** [comment]
Thanks @megakoresh  ! 🎉

**Pull request merged**
